### ISSUE TITLE
Inference with a trained model

### ISSUE THREAD

**Issue by gorjanradevski** [longzw1997/Open-GroundingDino#17]
Hello and thanks for open sourcing a GroundingDino training code! In addition, since the API is somewhat updated, I'm wondering whether you can also release a standalone inference notebook - similar to: https://github.com/IDEA-Research/GroundingDINO/blob/main/test.ipynb?

**Comment by BIGBALLON** [comment]
Hi, @gorjanradevski.
Because the models are exactly the same, I think you can directly reuse the test [notebook](https://github.com/IDEA-Research/GroundingDINO/blob/main/test.ipynb) in the original [GroundingDINO](https://github.com/IDEA-Research/GroundingDINO/tree/main) repo, just replace the corresponding positions of the weights.

``` python
model = load_model("groundingdino/config/GroundingDINO_SwinT_OGC.py", 
"path/to/weights/groundingdino_swint_xxx.pth")
```

**Comment by BIGBALLON** [comment]
Because the model architecture has not changed, you only need to **install** [GroundingDINO](https://github.com/IDEA-Research/GroundingDINO) library and then run [inference_on_a_image.py](/Users/bigballon/Downloads/Open-GroundingDino/tools/inference_on_a_image.py) to inference your images.

``` bash
python tools/inference_on_a_image.py \
  -c tools/GroundingDINO_SwinT_OGC.py \
  -p path/to/your/ckpt.pth \
  -i ./figs/dog.jpeg \
  -t "dog" \
  -o output
```

here is the visualization:


| Prompt |        Official ckpt         |        COCO ckpt         |        1.8M ckpt         |
| :----: | :--------------------------: | :----------------------: | :----------------------: |
|  dog   | ![](https://github.com/longzw1997/Open-GroundingDino/tree/main/figs/figs/dog-official.jpg) | ![](https://github.com/longzw1997/Open-GroundingDino/tree/main/figs/figs/dog-coco.jpg) | ![](https://github.com/longzw1997/Open-GroundingDino/tree/main/figs/figs/dog-1.8m.jpg) |
|  cat   | ![](https://github.com/longzw1997/Open-GroundingDino/tree/main/figs/figs/cat-official.jpg) | ![](https://github.com/longzw1997/Open-GroundingDino/tree/main/figs/figs/cat-coco.jpg) | ![](https://github.com/longzw1997/Open-GroundingDino/tree/main/figs/figs/cat-1.8m.jpg) |
