### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by doublejtoh** [longzw1997/Open-GroundingDino#19]
Thank you for your great work, 

i have several questions w.r.t. dataset preparation for pre-training.

1. How can I get the label map of COCO?

below might be the one, but I'm not quite sure...
https://github.com/longzw1997/Open-GroundingDino/blob/main/data_format.md#label_map

2. How can I get the annotation and label map of Object365 and LVIS?

i guess I might easily get label map of Objects365 and LVIS by referring to [this](https://github.com/longzw1997/Open-GroundingDino/blob/main/data_format.md#label_map) format,
but the code for generating the anno (objects365_train_odvg.json, lvis_v1_train_odvg.jsonl) seems not to exist.
For this, should I modify some part of [this COCO annotation generation script](https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/coco2odvg.py)? Or are there any alternatives?

3. How can I get the label map of GRIT-200k and flickr30k?

for obtaining ```grit_odvg_2m.json```, am I right to execute the [grit2odvg.py](https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/grit2odvg.py) with the ```--random_samples``` option to be set as 200000 (200k)?
I'm bit confused whether I should put this value to 200k or 2m.

Also for flickr30k, when running [flickr30ke2odvg.py](https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/flickr30ke2odvg.py), am I right to put the ```--osoi=False``` for generating flickr30k_entities_odvg_158k.json? I'm also bit confused about the meaning of 158k in the postfix.

I really appreciate for your response in advance and for your valuable work!

**Comment by BIGBALLON** [comment]
Hi, 
1. Sure, you are right, [this is the label_map](https://github.com/longzw1997/Open-GroundingDino/blob/main/data_format.md#label_map) of COCO
2. see 4
3. as for flickr30k, please see this issue https://github.com/longzw1997/Open-GroundingDino/issues/15
4. as for other datasets(GRIT-200k, CMCC,  LVIS, O365, V3Det, etc.), because the formats of different data sets may be inconsistent, you may rewrite the script in [tools](https://github.com/longzw1997/Open-GroundingDino/tree/main/tools) to process specific annotation files. There is no one-click conversion script here. If your dataset anno is coco format, simply modify [v3det2odvg.py](https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/v3det2odvg.py) to process it
