### ISSUE TITLE
Error: "Failed to load custom C++ ops. Running on CPU mode Only!"

### ISSUE THREAD

**Issue by formance** [longzw1997/Open-GroundingDino#7]
![image](https://github.com/longzw1997/Open-GroundingDino/assets/29134651/7c5e6012-290a-4bc5-9cf5-7f8f5ce23480)
请问是对单卡的显存要求高吗

**Comment by lanhas** [comment]
![image](https://github.com/longzw1997/Open-GroundingDino/assets/38825678/16b2d9b2-05e7-464c-b19a-116600f909a0)

**Comment by BIGBALLON** [comment]
Hi, @formance, plz make sure you build the CUDA ops following the [README.md](https://github.com/longzw1997/Open-GroundingDino/blob/main/README.md) :

``` bash
pip install -r requirements.txt 
cd models/GroundingDINO/ops
python setup.py build install
# unit test (should see all checking is True)
python test.py
```

**Comment by formance** [comment]
> Hi, @formance, plz make sure you build the CUDA ops following the [README.md](https://github.com/longzw1997/Open-GroundingDino/blob/main/README.md) :
> 
> ```shell
> pip install -r requirements.txt 
> cd models/GroundingDINO/ops
> python setup.py build install
> # unit test (should see all checking is True)
> python test.py
> ```

i have done this step, 
![image](https://github.com/longzw1997/Open-GroundingDino/assets/29134651/3721030a-60b6-4209-97a5-ba36b0061bb6)
but in unit test, cuda out of memory
![image](https://github.com/longzw1997/Open-GroundingDino/assets/29134651/dc5b3188-ad31-46dc-8ae8-9c3ddbb77280)
environment: pytorch 2.0.1, cuda 11.7, python 3.10.11

**Comment by BIGBALLON** [comment]
Hi, @formance, glad to hear you compiled it successfully.

this ``test.py`` file will test ops for channels 30 to 3096:

https://github.com/longzw1997/Open-GroundingDino/blob/9036724fad8d71ca1234e869da47bed0157d0fa0/models/GroundingDINO/ops/test.py#L81-L86

According to your operation log, 30, 32, 64, 71, and 1025 can all run normally. So maybe the error is caused by the fact that 4090 only has 20G GPU memory and V100 has 32G memory. It seems that your operator was compiled successfully

**Comment by formance** [comment]
> Hi, @formance, glad to hear you compiled it successfully.
> 
> this `test.py` file will test ops for channels 30 to 3096:
> 
> https://github.com/longzw1997/Open-GroundingDino/blob/9036724fad8d71ca1234e869da47bed0157d0fa0/models/GroundingDINO/ops/test.py#L81-L86
> 
> According to your log, 30, 32, 64, 71, and 1025 can all run normally. So maybe the error is caused by the fact that RTX4090 only has 20G GPU memory and V100 has 32G memory. It seems that your operator was compiled successfully, you can continue to try the following steps to see if everything works properly.

then why erro occured when training 
![image](https://github.com/longzw1997/Open-GroundingDino/assets/29134651/d8b409bc-bd68-408d-bbf7-f865d6d8f01b)

**Comment by BIGBALLON** [comment]
from https://github.com/IDEA-Research/GroundingDINO/blob/60d796825e1266e56f7e4e9e00e88de662b67bd3/README.md

## :hammer_and_wrench: Install 

**Note:**

0. If you have a CUDA environment, please make sure the environment variable `CUDA_HOME` is set. It will be compiled under CPU-only mode if no CUDA available.

Please make sure following the installation steps strictly, otherwise the program may produce: 
```bash
NameError: name '_C' is not defined
```

If this happened, please reinstalled the groundingDINO by reclone the git and do all the installation steps again.
 
#### how to check cuda:
```bash
echo $CUDA_HOME
```
If it print nothing, then it means you haven't set up the path/

Run this so the environment variable will be set under current shell. 
```bash
export CUDA_HOME=/path/to/cuda-11.3
```

Notice the version of cuda should be aligned with your CUDA runtime, for there might exists multiple cuda at the same time. 

If you want to set the CUDA_HOME permanently, store it using:

```bash
echo 'export CUDA_HOME=/path/to/cuda' >> ~/.bashrc
```
after that, source the bashrc file and check CUDA_HOME:
```bash
source ~/.bashrc
echo $CUDA_HOME
```

In this example, /path/to/cuda-11.3 should be replaced with the path where your CUDA toolkit is installed. You can find this by typing **which nvcc** in your terminal:

For instance, 
if the output is /usr/local/cuda/bin/nvcc, then:
```bash
export CUDA_HOME=/usr/local/cuda

**Comment by formance** [comment]
> from https://github.com/IDEA-Research/GroundingDINO/blob/60d796825e1266e56f7e4e9e00e88de662b67bd3/README.md
> 
> ```shell
> # your .bashrc file
> export CUDA_HOME=/usr/local/cuda-11.8
> export PATH=/usr/local/cuda-11.8/bin:$PATH
> export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH
> ```
> 
> ## 🛠️ Install
> **Note:**
> 
> 0. If you have a CUDA environment, please make sure the environment variable `CUDA_HOME` is set. It will be compiled under CPU-only mode if no CUDA available.
> 
> Please make sure following the installation steps strictly, otherwise the program may produce:
> 
> ```shell
> NameError: name '_C' is not defined
> ```
> 
> If this happened, please reinstalled the groundingDINO by reclone the git and do all the installation steps again.
> 
> #### how to check cuda:
> ```shell
> echo $CUDA_HOME
> ```
> 
> If it print nothing, then it means you haven't set up the path/
> 
> Run this so the environment variable will be set under current shell.
> 
> ```shell
> export CUDA_HOME=/path/to/cuda-11.3
> ```
> 
> Notice the version of cuda should be aligned with your CUDA runtime, for there might exists multiple cuda at the same time.
> 
> If you want to set the CUDA_HOME permanently, store it using:
> 
> ```shell
> echo 'export CUDA_HOME=/path/to/cuda' >> ~/.bashrc
> ```
> 
> after that, source the bashrc file and check CUDA_HOME:
> 
> ```shell
> source ~/.bashrc
> echo $CUDA_HOME
> ```
> 
> In this example, /path/to/cuda-11.3 should be replaced with the path where your CUDA toolkit is installed. You can find this by typing **which nvcc** in your terminal:
> 
> For instance, if the output is /usr/local/cuda/bin/nvcc, then:
> 
> ```shell
> export CUDA_HOME=/usr/local/cuda
> ```

i hava done this, but same error occured. maybe i know why.
![image](https://github.com/longzw1997/Open-GroundingDino/assets/29134651/6d0792e9-5f08-4f2a-8721-f6a5495c1fda)
the installed module name is not groundingdino._C ,is MultiScaleDeformableAttention
![image](https://github.com/longzw1997/Open-GroundingDino/assets/29134651/4b1fb683-87e3-4bb8-892e-644e96dc52a5)
i think u should fix it.

**Comment by BIGBALLON** [comment]
This PR fixed this issue

https://github.com/longzw1997/Open-GroundingDino/pull/10

**Comment by formance** [comment]
thanks.
